FROM ubuntu:20.04
RUN apt-get update && apt-get install -y apt-utils python3.8 python3-pip
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pipenv
COPY Pipfile .
COPY Pipfile.lock .
RUN pipenv install --deploy --python /usr/bin/python3.8
COPY ./relayer ./relayer
COPY ./chain_simulator ./chain_simulator
ENTRYPOINT [ "pipenv", "run", "python", "-u", "relayer/main.py" ]